day09aixianfeng/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns= [


    url(r'^$',views.home,name='home'),
    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),
    url(r'^mine/$',views.mine,name='mine'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^register/$',views.register,name='register'),
    url(r"^login/$",views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^subcart/$',views.subcart,name='subcart'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^changecartselect/$',views.changecartselect,name='changecartselect'),
    url(r'^changeall/$',views.changeall,name='changeall'),
    url(r'^generateorder/$', views.generateorder, name='generateorder'),  # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'),  # 订单列表
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),  # 订单详情
#支付宝
    url(r'^returnurl/$', views.returnurl, name='returnurl'),  # 支付成功后，客户端的显示
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'),  # 支付成功后，订单的处理
    url(r'^pay/$', views.pay, name='pay'),  # 支付

]

day09aixianfeng/day09aixianfeng/urls.py
"""day09aixianfeng URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Functi on views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('axf.urls',namespace='axf')),


]

day09aixianfeng/axf/models.py
from django.db import models

# Create your models here.

class Base(models.Model):
    img=models.CharField(max_length=100)
    name=models.CharField(max_length=100)
    trackid=models.CharField(max_length=20)
    class Meta:
        abstract=True
    def __str__(self):
        return self.name


class Wheel(Base):
    class Meta:
        db_table='axf_wheel'

class Nav(Base):
    class Meta:
        db_table='axf_nav'
class Mustbuy(Base):
    class Meta:
        db_table='axf_mustbuy'

class Shop(Base):
    class Meta:
        db_table='axf_shop'

class Mainshow(models.Model):
    trackid = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=100)

    img1 = models.CharField(max_length=100)
    childcid1 = models.CharField(max_length=10)
    productid1 = models.CharField(max_length=10)
    longname1 = models.CharField(max_length=100)
    price1 = models.CharField(max_length=10)
    marketprice1 = models.CharField(max_length=10)

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=10)
    productid2 = models.CharField(max_length=10)
    longname2 = models.CharField(max_length=100)
    price2 = models.CharField(max_length=10)
    marketprice2 = models.CharField(max_length=10)

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=10)
    productid3 = models.CharField(max_length=10)
    longname3 = models.CharField(max_length=100)
    price3 = models.CharField(max_length=10)
    marketprice3 = models.CharField(max_length=10)

    class Meta:
        db_table = 'axf_mainshow'

class Foodtype(models.Model):
    # 分类ID
    typeid = models.CharField(max_length=10)
    # 分类名称
    typename = models.CharField(max_length=100)
    # 子类(多个)
    childtypenames = models.CharField(max_length=200)
    # 排序
    typesort = models.IntegerField()

    class Meta:
        db_table = 'axf_foodtypes'


class Goods(models.Model):
    # 商品ID
    productid = models.CharField(max_length=10)
    # 商品图片
    productimg = models.CharField(max_length=100)
    # 商品名称
    productname = models.CharField(max_length=100)
    # 商品长名字
    productlongname = models.CharField(max_length=256)
    # 是否精选
    isxf = models.IntegerField()
    # 是否买一送一
    pmdesc = models.IntegerField()
    # 商品规格
    specifics = models.CharField(max_length=100)
    # 商品价格
    price = models.DecimalField(max_digits=6,decimal_places=2)
    # 商品超市价格
    marketprice = models.DecimalField(max_digits=6, decimal_places=2)
    # 分类ID
    categoryid = models.IntegerField()
    # 子类ID
    childcid = models.IntegerField()
    # 子类名称
    childcidname = models.CharField(max_length=100)
    # 详情页ID
    dealerid = models.CharField(max_length=10)
    # 库存
    storenums = models.IntegerField()
    # 销售
    productnum = models.IntegerField()

    class Meta:
        db_table = 'axf_goods'

class User(models.Model):
    # 邮箱
    email = models.EmailField(max_length=40, unique=True,null=False)
    # 密码
    password = models.CharField(max_length=256)
    # 昵称
    name = models.CharField(max_length=100,null=False)
    # 头像
    img = models.CharField(max_length=40, default='axf.png')
    # 等级
    rank = models.IntegerField(default=1)
    token=models.CharField(max_length=255,default='')

    class Meta:
         db_table = 'axf_user'

class Cart(models.Model):
    # 用户 [添加的这个商品属于哪个用户]
    user = models.ForeignKey(User)

    # 商品 [添加的是哪个商品]
    goods = models.ForeignKey(Goods)

    ## 具体规格 [颜色、内存、版本、大小.....]
    # 商品数量
    number = models.IntegerField()

    # 是否选中
    isselect = models.BooleanField(default=True)
    # 是否删除
    isdelete = models.BooleanField(default=False)

    class Meta:
        db_table = 'axf_cart'


# 订单 模型类
# 一个用户 对应 多个订单
class Order(models.Model):
    # 用户
    user = models.ForeignKey(User)
    # 创建时间
    createtime = models.DateTimeField(auto_now_add=True)
    # 更新时间
    updatetime = models.DateTimeField(auto_now=True)
    # 状态
    # -1 过期
    # 0 未付款
    # 1 已付款，待发货
    # 2 已发货，待收货
    # 3 已收货，待评价
    # 4 已评价
    status = models.IntegerField(default=0)
    # 订单号
    identifier = models.CharField(max_length=256)



# 订单商品 模型类
# 一个订单 对应 多个商品(订单商品)
class OrderGoods(models.Model):
    # 订单
    order = models.ForeignKey(Order)
    # 商品
    goods = models.ForeignKey(Goods)

    ## 商品选择规格
    number = models.IntegerField()

day09aixianfeng/templates/order/orderdetail.html
{% extends 'base/base.html' %}
{% load static %}


{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'order/js/orderdetail.js' %}"></script>
{% endblock %}

{% block title %}
    订单详情
{% endblock %}

{% block content %}
    <div class="cart">
    <div class="back" style="position: relative;left: 550px">
            <a href="{% url 'axf:orderlist' %}">
                <span class=" glyphicon glyphicon-remove " style="size: 10em"></span>
            </a>
        </div>

            <p style="color: red">订单号: {{ order.identifier }}</p>

        <ul>
            {% for ordergoods in order.ordergoods_set.all %}
            <li>
            <div class="content-wrapper">
                <div class="img">
                &nbsp;<img src="{{ ordergoods.goods.productimg }}" alt="">
                </div>
                <div class="detail">
                <p class="name">{{ ordergoods.goods.productlongname }}</p>
                <p class="price" >{{ ordergoods.goods.price }}</p>
                <p class="num">x{{ ordergoods.number }}</p>
                </div>
            </div>
            </li>
            {% endfor %}
        </ul>


        <div class="bill">
            <div class="bill-left">

                <div class="total">
                    <span>￥</span>
                    <b>{{ sum }}</b>
                </div>
            </div>

{% if order.status == 0%}
 <button class="bill-right" id="alipay" data-orderid="{{ order.id }}">支付
{% endif %}



{#                    < class="btn btn-default" id="alipay" data-orderid="{{ order.id }}"></button>#}

 </button>

    </div>
    </div>

{% endblock %}

day09aixianfeng/templates/order/orderlist.html
{% extends 'base/base.html' %}
{% load static %}
{% block footer %}
{% endblock %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'order/css/orderlist.css' %}">
{% endblock %}



{% block title %}
    订单列表
{% endblock %}

{% block content %}

    <div class="cart">
     <div class="back" style="position: relative;left: 550px">
            <a href="{% url 'axf:mine' %}">
                <span class=" glyphicon glyphicon-remove " style="size: 10em"></span>
            </a>
        </div>
        <ul>
        {% for order in orders %}
            <li>

                <a href="{% url 'axf:orderdetail' order.identifier %}">
                    订单号: {{ order.identifier }} ----
                    {% if order.status == 0 %}
                        未付款
                    {% elif order.status == 1 %}
                        待发货
                    {% elif order.status == 2 %}
                        待收货
                    {% elif order.status == 3 %}
                        待评价
                    {% elif order.status == 4 %}
                        已评价
                    {% endif %}
                </a>
                <br>
              <i class="img">
            {% for item in order.ordergoods_set.all %}
                    <img src="{{ item.goods.productimg }}" alt="">
            {% endfor %}
            </i>
            </li>

            <br>
        {% endfor %}
        </ul>
    </div>


{% endblock %}